version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "install php 8.1"
  pre_build:
    commands:
      - php -v
      - echo ${CODEBUILD_WEBHOOK_TRIGGER#branch/}
  build:
    commands:
      - echo "Hello, World! (phase=build)"
      - ls -al
  post_build:
    commands:
      - echo "Hello, World! (phase=post_build)"