version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo "install php 7.4"
  pre_build:
    commands:
      - php -v
      - echo ${CODEBUILD_WEBHOOK_TRIGGER#branch/}
      - cd app/
      - php composer.phar install
      - php artisan test
  build:
    commands:
      - echo "Hello, World! (phase=build)"
      - ls -al
  post_build:
    commands:
      - echo "Hello, World! (phase=post_build)"